### ISSUE TITLE
SPF Examples - Pictures Mismatched

### ISSUE THREAD

**Issue by dtbray** [duocircle/Office365-Setup-DKIM-DMARC-SPF#1]
Hi!  Your 'no spf record' and 'soft-fail spf record' screenshots (of geocities.com and dell.com respectively) are reversed relative to your text.  Just needs a quick re-link to fix the order of the screenshots.  Thanks for the awesome guide!

**Comment by bslavin** [comment]
think this was resolved. Thank you
